#!/bin/bash
# Generated by Diego Valenzuela. License: Unlicense.
# Below you must manually list the buckets:
buckets=(
  "<bucket-1>"
  "<bucket-2>"
)

for bucket in "${buckets[@]}"
do
  echo "🔍 Checking bucket: $bucket"

  # Check bucket policy for public access
  aws s3api get-bucket-policy --bucket "$bucket" 2>/dev/null | \
  jq -r '.Policy' | grep -E 's3:GetObject|s3:PutObject|s3:ListBucket' && \
  echo "⚠️  [$bucket] Potential public access via bucket policy (Unholy Trinity detected)" || \
  echo "✅ [$bucket] No dangerous policy actions."

  # Check ACL for public grants
  aws s3api get-bucket-acl --bucket "$bucket" 2>/dev/null | \
  jq '.Grants[] | select(.Grantee.URI != null) | select(.Grantee.URI | test("AllUsers|AuthenticatedUsers")) | .Permission' && \
  echo "⚠️  [$bucket] Public access via ACL" || \
  echo "✅ [$bucket] No public ACL access."

  # Check public access block config
  echo "🔒 Public Access Block:"
  aws s3api get-bucket-public-access-block --bucket "$bucket" 2>/dev/null | jq '.'

  echo "-----------------------------"
done
